### ISSUE TITLE
mountain.html

### ISSUE THREAD

**Issue by bquetmelanee** [bquetmelanee/IT115#2]
> Goal: Populate the `mountain.html` page with content about the mountains and style it according to the project’s theme.
> 
> Requirements:
> - Add a header with the mountain name/title.
> - Include at least two images of mountains with captions.
> - Add descriptive paragraphs detailing mountain features, popular trails, and best visiting seasons.
> - Apply CSS to ensure text and images are aligned and styled consistently with the project’s design.
> 
> Acceptance Criteria:
> - The `mountain.html` page displays a header, images with captions, and description text.
> - All elements are responsive and display correctly on desktop and mobile views.
>  
> ### The beautiful Mountains in the PNW area ### 
> The best visiting season is the summer from July to September
> 

1. > Some hiking trails to visit are: 
2. > Skyline Trail loop — Mount Rainier National Park | Intermediate
3. > Snow Lake Trail — Mt. Baker-Snoqualmie National Forest | Intermediate
4. > Mount Si — North Bend, Washington | Expert

![Image](https://github.com/user-attachments/assets/55959997-bafa-458e-9efc-0328cd7bed59)
![Image](https://github.com/user-attachments/assets/e43f836d-f688-4ea3-b7af-deaf1168cb62)

**Comment by Ammani-hash** [comment]
As an outdoors enthusiast, I love exploring the PNW's iconic mountains and trails.

**Comment by Ammani-hash** [comment]
Here is the populated html document about mountains. I have attached it below.
